services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=${POSTGRES_DATABASE}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata: