server.port=8090

# Spring Data JPA
spring.datasource.url=${SPRING_DATASOURCE_DEV_URL}
spring.datasource.username=${POSTGRES_USER_DEV}
spring.datasource.password=${POSTGRES_PASSWORD_DEV}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# para cargar los datos del archivo sql de pruebas
spring.sql.init.mode=always

langchain4j.open-ai.chat-model.log-responses=true
langchain4j.open-ai.chat-model.log-requests=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG